"""Generate Workbench Alpha frontend API contracts from Pydantic models."""

from __future__ import annotations

import json
from pathlib import Path

from tqe.workshop.app_service import WORKBENCH_RESPONSE_MODELS

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "apps/workbench-alpha/src/generated"
SCHEMA_PATH = OUT_DIR / "api-schemas.json"
TYPES_PATH = OUT_DIR / "api-types.ts"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    schemas = {
        name: model.model_json_schema(ref_template="#/$defs/{model}")
        for name, model in sorted(WORKBENCH_RESPONSE_MODELS.items())
    }
    SCHEMA_PATH.write_text(
        json.dumps(schemas, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    schema_literal = json.dumps(schemas, indent=2, sort_keys=True)
    TYPES_PATH.write_text(
        "\n".join(
            [
                "/* Generated by scripts/workbench_alpha/generate_contracts.py. */",
                'import type { FromSchema } from "json-schema-to-ts";',
                "",
                f"export const apiSchemas = {schema_literal} as const;",
                "",
                *[
                    f'export type {name} = FromSchema<typeof apiSchemas["{name}"]>;'
                    for name in sorted(schemas)
                ],
                "",
            ]
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
