"""Default M1.1 primitive, relation, and operator catalog."""

from __future__ import annotations

from tqe.runtime.ir import (
    CapabilityCatalog,
    Cardinality,
    CatalogEntry,
    CatalogInput,
    CatalogOutput,
    ComplexityLimits,
    EntityScope,
    MissingDataSemantics,
    NodeKind,
    OperatorSignature,
    ParameterDefinition,
    PayloadType,
    TemporalContainer,
    TypedValue,
    Unit,
)


def output(
    *,
    name: str,
    temporal_type: TemporalContainer,
    payload_type: PayloadType,
    cardinality: Cardinality,
    unit: Unit = Unit.NONE,
    entity_scope: EntityScope = EntityScope.NONE,
    evidence_fields: list[str] | None = None,
    allowed_values: list[str] | None = None,
    missing_data_semantics: MissingDataSemantics = MissingDataSemantics.UNKNOWN,
) -> CatalogOutput:
    return CatalogOutput(
        name=name,
        temporal_type=temporal_type,
        payload_type=payload_type,
        cardinality=cardinality,
        unit=unit,
        entity_scope=entity_scope,
        missing_data_semantics=missing_data_semantics,
        evidence_fields=evidence_fields or [],
        allowed_values=allowed_values,
    )


def input_ref(
    *,
    name: str,
    temporal_type: TemporalContainer,
    payload_type: PayloadType,
    cardinality: Cardinality,
    unit: Unit = Unit.NONE,
    entity_scope: EntityScope = EntityScope.NONE,
    required: bool = True,
) -> CatalogInput:
    return CatalogInput(
        name=name,
        temporal_type=temporal_type,
        payload_type=payload_type,
        cardinality=cardinality,
        unit=unit,
        entity_scope=entity_scope,
        required=required,
    )


def parameter(
    *,
    name: str,
    payload_type: PayloadType,
    description: str,
    unit: Unit = Unit.NONE,
    required: bool = False,
    default: TypedValue | None = None,
    minimum: float | None = None,
    maximum: float | None = None,
    allowed_values: list[str] | None = None,
) -> ParameterDefinition:
    return ParameterDefinition(
        name=name,
        payload_type=payload_type,
        unit=unit,
        required=required,
        default=default,
        minimum=minimum,
        maximum=maximum,
        allowed_values=allowed_values,
        description=description,
    )


def typed_number(value: float, unit: Unit) -> TypedValue:
    return TypedValue(payload_type=PayloadType.NUMBER, unit=unit, value=value)


def typed_enum(value: str) -> TypedValue:
    return TypedValue(payload_type=PayloadType.ENUM, unit=Unit.NONE, value=value)


def primitive(
    *,
    name: str,
    version: str,
    purpose: str,
    outputs: list[CatalogOutput],
    evidence_fields: list[str],
    inputs: list[CatalogInput] | None = None,
    parameters: list[ParameterDefinition] | None = None,
    limitations: list[str] | None = None,
    missing_data_semantics: MissingDataSemantics = MissingDataSemantics.UNKNOWN,
) -> CatalogEntry:
    return CatalogEntry(
        name=name,
        version=version,
        kind=NodeKind.PRIMITIVE,
        purpose=purpose,
        inputs=inputs or [],
        outputs=outputs,
        parameters=parameters or [],
        limitations=limitations or [],
        missing_data_semantics=missing_data_semantics,
        evidence_fields=evidence_fields,
    )


def relation(
    *,
    name: str,
    version: str,
    purpose: str,
    outputs: list[CatalogOutput],
    evidence_fields: list[str],
    inputs: list[CatalogInput] | None = None,
    parameters: list[ParameterDefinition] | None = None,
    limitations: list[str],
    missing_data_semantics: MissingDataSemantics = MissingDataSemantics.UNKNOWN,
) -> CatalogEntry:
    return CatalogEntry(
        name=name,
        version=version,
        kind=NodeKind.RELATION,
        purpose=purpose,
        inputs=inputs or [],
        outputs=outputs,
        parameters=parameters or [],
        limitations=limitations,
        missing_data_semantics=missing_data_semantics,
        evidence_fields=evidence_fields,
    )


def default_primitives() -> list[CatalogEntry]:
    return [
        primitive(
            name="possession_segment",
            version="0.1.0",
            purpose="Identify active-ball possession intervals for the perspective team.",
            outputs=[
                output(
                    name="episodes",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.POSSESSION,
                    evidence_fields=[
                        "possession_start_frame_id",
                        "possession_end_frame_id",
                        "possession_duration_seconds",
                    ],
                ),
                output(
                    name="anchors",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "start_frame_id",
                        "end_frame_id",
                    ],
                ),
            ],
            evidence_fields=[
                "possession_start_frame_id",
                "possession_end_frame_id",
                "possession_duration_seconds",
            ],
        ),
        primitive(
            name="controlled_pass_episode",
            version="0.1.0",
            purpose=(
                "Identify completed pass actions where event data supplies the "
                "candidate passer/receiver and tracking proves physical release "
                "plus controlled reception."
            ),
            outputs=[
                output(
                    name="episodes",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.POSSESSION,
                    evidence_fields=[
                        "pass_episode_id",
                        "passer_id",
                        "receiver_id",
                        "event_anchor_frame_id",
                        "physical_release_frame_id",
                        "controlled_reception_frame_id",
                        "release_match_time_ms",
                        "reception_match_time_ms",
                        "controlled_pass_status",
                        "release_control_status",
                        "controlled_reception_status",
                        "possession_continuity_status",
                        "release_ball_point",
                        "reception_ball_point",
                        "release_passer_point",
                        "reception_receiver_point",
                        "forward_progression_m",
                        "controlled_pass_status",
                    ],
                ),
                output(
                    name="anchors",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "start_frame_id",
                        "end_frame_id",
                        "pass_episode_id",
                        "passer_id",
                        "receiver_id",
                        "controlled_pass_status",
                        "forward_progression_m",
                    ],
                ),
                output(
                    name="controlled_pass_status",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.POSSESSION,
                    allowed_values=["PASS", "FAIL", "UNKNOWN"],
                    evidence_fields=[
                        "controlled_pass_status",
                        "release_detection_status",
                        "controlled_reception_status",
                    ],
                ),
                output(
                    name="forward_progression_m",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.NUMBER,
                    cardinality=Cardinality.SINGLE,
                    unit=Unit.METRE,
                    entity_scope=EntityScope.POSSESSION,
                    evidence_fields=["forward_progression_m"],
                ),
            ],
            parameters=[
                parameter(
                    name="release_search_before_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    default=typed_number(1.0, Unit.SECOND),
                    minimum=0.0,
                    maximum=5.0,
                    description="Search window before the event anchor for passer control.",
                ),
                parameter(
                    name="release_search_after_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    default=typed_number(3.0, Unit.SECOND),
                    minimum=0.0,
                    maximum=8.0,
                    description="Search window after the event anchor for ball departure.",
                ),
                parameter(
                    name="reception_search_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    default=typed_number(6.0, Unit.SECOND),
                    minimum=0.2,
                    maximum=15.0,
                    description="Maximum release-to-controlled-reception search window.",
                ),
                parameter(
                    name="control_distance_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    default=typed_number(2.5, Unit.METRE),
                    minimum=0.1,
                    maximum=8.0,
                    description="Maximum ball-player distance for control evidence.",
                ),
                parameter(
                    name="nearest_teammate_margin_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    default=typed_number(1.0, Unit.METRE),
                    minimum=0.0,
                    maximum=5.0,
                    description="Margin allowing the intended player to count as controlling near teammates.",
                ),
                parameter(
                    name="minimum_receiver_dwell_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    default=typed_number(0.24, Unit.SECOND),
                    minimum=0.04,
                    maximum=2.0,
                    description="Minimum receiver-control dwell for controlled reception.",
                ),
            ],
            evidence_fields=[
                "pass_episode_id",
                "passer_id",
                "receiver_id",
                "event_anchor_frame_id",
                "physical_release_frame_id",
                "controlled_reception_frame_id",
                "release_ball_point",
                "reception_ball_point",
                "release_passer_point",
                "reception_receiver_point",
                "controlled_pass_status",
                "release_control_status",
                "controlled_reception_status",
                "possession_continuity_status",
                "forward_progression_m",
                "controlled_pass_status",
            ],
            limitations=[
                "Uses event data for candidate passes and tracking data for release/reception proof.",
                "Does not infer tactical intention, pass optimality, or decision quality.",
            ],
        ),
        primitive(
            name="defensive_line_model",
            version="0.1.0",
            purpose=(
                "Fit an observed geometric defensive line at supplied anchor frames "
                "from defending outfield player tracking positions."
            ),
            inputs=[
                input_ref(
                    name="anchors",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                ),
            ],
            outputs=[
                output(
                    name="anchor_evaluations",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "line_status",
                        "line_reason",
                        "line_type",
                        "line_x_m",
                        "normalized_line_x_m",
                        "defensive_line_player_ids",
                        "defenders_goal_side_count",
                        "line_compactness_m",
                        "candidate_line_count",
                        "goal_side_buffer_m",
                        "line_band_width_m",
                        "minimum_line_defenders",
                    ],
                ),
                output(
                    name="line_status",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.ANCHOR,
                    allowed_values=["PASS", "FAIL", "UNKNOWN"],
                    evidence_fields=["line_status", "line_reason"],
                ),
            ],
            parameters=[
                parameter(
                    name="goal_side_buffer_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    default=typed_number(1.0, Unit.METRE),
                    minimum=0.0,
                    maximum=10.0,
                    description="Minimum distance beyond the ball for a defender to count as goal-side.",
                ),
                parameter(
                    name="line_band_width_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    default=typed_number(2.0, Unit.METRE),
                    minimum=0.1,
                    maximum=15.0,
                    description="Maximum normalized x-span of defenders in one observed line band.",
                ),
                parameter(
                    name="minimum_line_defenders",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.COUNT,
                    default=typed_number(4, Unit.COUNT),
                    minimum=2,
                    maximum=10,
                    description="Minimum defending outfield players required to form an observed line.",
                ),
            ],
            evidence_fields=[
                "anchor_id",
                "anchor_frame_id",
                "line_status",
                "line_reason",
                "line_x_m",
                "normalized_line_x_m",
                "defensive_line_player_ids",
                "defender_positions_used",
            ],
            limitations=[
                "Models only an observed geometric defensive line under declared thresholds.",
                "Does not identify a tactical first, second, midfield, or back line.",
                "Does not prove a line break, tactical intention, pass optimality, or defensive intent.",
            ],
        ),
        primitive(
            name="relative_position_to_line",
            version="0.1.0",
            purpose=(
                "Classify an entity position as ahead of, behind, or level with "
                "an observed line at a declared frame."
            ),
            inputs=[
                input_ref(
                    name="line_evaluations",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                ),
                input_ref(
                    name="entity_anchors",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                ),
            ],
            outputs=[
                output(
                    name="anchor_evaluations",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "relative_position_status",
                        "relative_position_reason",
                        "entity_id",
                        "entity_frame_id",
                        "line_x_m",
                        "entity_x_m",
                        "normalized_line_x_m",
                        "normalized_entity_x_m",
                        "signed_distance_to_line_m",
                        "distance_to_line_m",
                        "line_buffer_m",
                    ],
                ),
                output(
                    name="relative_position_status",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.ANCHOR,
                    allowed_values=[
                        "AHEAD_OF_LINE",
                        "BEHIND_LINE",
                        "LEVEL_WITH_LINE",
                        "UNKNOWN",
                    ],
                    evidence_fields=["relative_position_status", "relative_position_reason"],
                ),
            ],
            parameters=[
                parameter(
                    name="entity_id_field",
                    payload_type=PayloadType.ENUM,
                    unit=Unit.NONE,
                    default=typed_enum("receiver_id"),
                    allowed_values=["receiver_id", "passer_id"],
                    description="Entity-reference field read from the entity anchor record.",
                ),
                parameter(
                    name="entity_frame_field",
                    payload_type=PayloadType.ENUM,
                    unit=Unit.NONE,
                    default=typed_enum("controlled_reception_frame_id"),
                    allowed_values=[
                        "controlled_reception_frame_id",
                        "physical_release_frame_id",
                        "anchor_frame_id",
                    ],
                    description="Frame field at which the entity position is evaluated.",
                ),
                parameter(
                    name="line_buffer_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    default=typed_number(0.5, Unit.METRE),
                    minimum=0.0,
                    maximum=10.0,
                    description="Distance from the line treated as level rather than ahead or behind.",
                ),
            ],
            evidence_fields=[
                "anchor_id",
                "anchor_frame_id",
                "relative_position_status",
                "relative_position_reason",
                "entity_id",
                "entity_frame_id",
                "signed_distance_to_line_m",
            ],
            limitations=[
                "Classifies only observed position relative to a supplied geometric line.",
                "Does not identify a tactical first, second, midfield, or back line.",
                "Does not prove a line break, tactical intention, pass optimality, or defensive intent.",
            ],
        ),
        primitive(
            name="ball_lateral_fraction",
            version="0.1.0",
            purpose="Normalize ball distance from pitch centerline toward either touchline.",
            outputs=[
                output(
                    name="fraction",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.NUMBER,
                    cardinality=Cardinality.SINGLE,
                    unit=Unit.FRACTION,
                    entity_scope=EntityScope.BALL,
                    evidence_fields=["wide_entry_y_m", "ball_side"],
                )
            ],
            evidence_fields=["wide_entry_y_m", "ball_side"],
            limitations=["Depends on canonical pitch coordinates and known pitch width."],
        ),
        primitive(
            name="defensive_outfield_centroid",
            version="0.1.0",
            purpose="Measure defending outfield team centroid without goalkeeper bias.",
            outputs=[
                output(
                    name="centroid_y",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.NUMBER,
                    cardinality=Cardinality.PER_TEAM,
                    unit=Unit.METRE,
                    entity_scope=EntityScope.TEAM,
                    evidence_fields=["baseline_defensive_centroid_y_m"],
                )
            ],
            evidence_fields=["baseline_defensive_centroid_y_m", "defending_team_id"],
            limitations=["Goalkeepers are excluded from the outfield centroid."],
        ),
        primitive(
            name="signed_lateral_shift",
            version="0.1.0",
            purpose="Measure defensive centroid movement toward the ball side.",
            outputs=[
                output(
                    name="signed_shift",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.NUMBER,
                    cardinality=Cardinality.SINGLE,
                    unit=Unit.METRE,
                    entity_scope=EntityScope.TEAM,
                    evidence_fields=[
                        "baseline_start_frame_id",
                        "baseline_end_frame_id",
                        "anchor_frame_id",
                        "signed_shift_metres",
                        "block_shift_score",
                    ],
                ),
                output(
                    name="anchors",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "start_frame_id",
                        "end_frame_id",
                    ],
                ),
            ],
            inputs=[
                input_ref(
                    name="possession_episodes",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.POSSESSION,
                ),
                input_ref(
                    name="entry_episodes",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.BALL,
                ),
                input_ref(
                    name="defensive_centroid",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.NUMBER,
                    cardinality=Cardinality.PER_TEAM,
                    unit=Unit.METRE,
                    entity_scope=EntityScope.TEAM,
                ),
            ],
            evidence_fields=[
                "baseline_start_frame_id",
                "baseline_end_frame_id",
                "anchor_frame_id",
                "signed_shift_metres",
                "block_shift_score",
            ],
        ),
        primitive(
            name="outcome_classification",
            version="0.1.0",
            purpose="Classify the post-anchor outcome under the frozen M1 predicates.",
            outputs=[
                output(
                    name="classification",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.POSSESSION,
                    evidence_fields=["classification", "outcome_frame_id"],
                )
            ],
            inputs=[
                input_ref(
                    name="accepted_shift_episodes",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.TEAM,
                ),
            ],
            parameters=[
                parameter(
                    name="horizon",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    required=True,
                    minimum=0.2,
                    maximum=30.0,
                    description="Outcome lookahead horizon in seconds.",
                )
            ],
            evidence_fields=["classification", "outcome_frame_id"],
            limitations=["Does not infer intent, optimality, or missed opportunity."],
        ),
        primitive(
            name="relation_destination_entry",
            version="0.1.0",
            purpose=(
                "Measure whether the ball enters the exact destination region of a "
                "relation episode inside a declared post-open window."
            ),
            outputs=[
                output(
                    name="entry_status",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.RELATION,
                    allowed_values=["PASS", "FAIL", "UNKNOWN"],
                    evidence_fields=[
                        "entry_status",
                        "relation_id",
                        "anchor_id",
                        "destination_entry_frame_id",
                        "time_to_entry_seconds",
                        "entry_mode",
                        "destination_region",
                        "destination_region_type",
                        "destination_region_bounds",
                        "destination_side",
                        "destination_lane",
                        "observed_window_start_frame_id",
                        "observed_window_end_frame_id",
                        "unknown_reason",
                        "missing_ball_frame_count",
                    ],
                )
            ],
            inputs=[
                input_ref(
                    name="relation_episodes",
                    temporal_type=TemporalContainer.RELATION_EPISODE_SET,
                    payload_type=PayloadType.RELATION_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.RELATION,
                )
            ],
            parameters=[
                parameter(
                    name="destination_entry_horizon_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    required=True,
                    minimum=0.2,
                    maximum=30.0,
                    description="Lookahead horizon for relation destination entry.",
                ),
                parameter(
                    name="result_id_seed",
                    payload_type=PayloadType.ENUM,
                    required=True,
                    description="Seed used to derive deterministic relation-entry record IDs.",
                ),
                parameter(
                    name="episode_selection",
                    payload_type=PayloadType.ENUM,
                    required=True,
                    allowed_values=["entry_first_then_progression", "first_by_duration_clearance"],
                    description="Deterministic witness ordering when an anchor has multiple relation episodes.",
                ),
            ],
            evidence_fields=[
                "entry_status",
                "relation_id",
                "anchor_id",
                "destination_entry_frame_id",
                "time_to_entry_seconds",
                "entry_mode",
                "destination_region",
                "destination_region_type",
                "destination_region_bounds",
                "destination_side",
                "destination_lane",
                "observed_window_start_frame_id",
                "observed_window_end_frame_id",
                "unknown_reason",
                "missing_ball_frame_count",
            ],
            limitations=[
                "Measures entry into relation destination geometry only.",
                "No pass probability, optimality, decision-quality, intent, causation, or missed-opportunity claim.",
            ],
        ),
        primitive(
            name="relation_destination_entry_classification",
            version="0.1.0",
            purpose=(
                "Classify whether the ball later enters the destination region of a "
                "previously evaluated relation episode."
            ),
            outputs=[
                output(
                    name="classification",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.RELATION,
                    evidence_fields=[
                        "classification",
                        "base_result_id",
                        "relation_id",
                        "destination_entry_frame_id",
                        "destination_region",
                        "destination_region_type",
                        "destination_region_bounds",
                        "destination_side",
                        "destination_lane",
                    ],
                )
            ],
            inputs=[
                input_ref(
                    name="relation_episodes",
                    temporal_type=TemporalContainer.RELATION_EPISODE_SET,
                    payload_type=PayloadType.RELATION_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.RELATION,
                )
            ],
            parameters=[
                parameter(
                    name="destination_entry_horizon_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    required=True,
                    minimum=0.2,
                    maximum=30.0,
                    description="Lookahead horizon for destination lane entry.",
                ),
                parameter(
                    name="result_id_seed",
                    payload_type=PayloadType.ENUM,
                    required=True,
                    description="Seed used to derive deterministic experimental result IDs.",
                ),
                parameter(
                    name="episode_selection",
                    payload_type=PayloadType.ENUM,
                    required=True,
                    allowed_values=["first_by_duration_clearance"],
                    description="Deterministic selection strategy when an anchor has multiple relation episodes.",
                ),
            ],
            evidence_fields=[
                "classification",
                "base_result_id",
                "relation_id",
                "destination_entry_frame_id",
                "destination_region",
                "destination_region_type",
                "destination_region_bounds",
                "destination_side",
                "destination_lane",
            ],
            limitations=[
                "Trusted recipe wrapper; agent-authored plans should use relation_destination_entry.",
                "Requires an upstream relation episode set.",
                "No pass probability, optimality, decision-quality, intent, or missed-opportunity claim.",
            ],
        ),
    ]


def default_relations() -> list[CatalogEntry]:
    return [
        relation(
            name="geometric_progressive_corridor",
            version="0.1.0",
            purpose=(
                "Represent a geometrically clear forward connection from the ball location "
                "to an attacking teammate over an interval."
            ),
            outputs=[
                output(
                    name="episodes",
                    temporal_type=TemporalContainer.RELATION_EPISODE_SET,
                    payload_type=PayloadType.RELATION_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.RELATION,
                    evidence_fields=[
                        "relation_id",
                        "open_frame_id",
                        "open_confirm_frame_id",
                        "close_frame_id",
                        "duration_seconds",
                        "target_player_id",
                        "destination_side",
                        "destination_region",
                        "destination_region_type",
                        "destination_region_bounds",
                        "destination_lane",
                        "minimum_clearance_m",
                        "limiting_defender_id",
                        "source_open_point",
                        "target_open_point",
                        "source_close_point",
                        "target_close_point",
                    ],
                ),
                output(
                    name="anchor_evaluations",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "evaluation_status",
                        "relation_count",
                        "witness_relation_id",
                        "unknown_reason",
                        "state_counts",
                    ],
                ),
            ],
            inputs=[
                input_ref(
                    name="anchors",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.POSSESSION,
                )
            ],
            parameters=[
                parameter(
                    name="max_window_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    required=True,
                    minimum=0.2,
                    maximum=15.0,
                    description="Maximum relation search window after the anchor.",
                ),
                parameter(
                    name="minimum_progression_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=80.0,
                    description="Minimum forward progression from source to target.",
                ),
                parameter(
                    name="minimum_segment_length_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=80.0,
                    description="Minimum source-target segment length.",
                ),
                parameter(
                    name="maximum_segment_length_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=100.0,
                    description="Maximum source-target segment length.",
                ),
                parameter(
                    name="minimum_clearance_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=40.0,
                    description="Minimum defender clearance from the source-target segment.",
                ),
                parameter(
                    name="open_after_frames",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.COUNT,
                    required=True,
                    minimum=1.0,
                    maximum=100.0,
                    description="Frames required before a corridor is considered open.",
                ),
                parameter(
                    name="close_after_frames",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.COUNT,
                    required=True,
                    minimum=1.0,
                    maximum=100.0,
                    description="Frames required before a corridor is considered closed.",
                ),
                parameter(
                    name="minimum_duration_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    required=True,
                    minimum=0.0,
                    maximum=15.0,
                    description="Minimum open duration retained in the relation output.",
                ),
                parameter(
                    name="side_filter",
                    payload_type=PayloadType.ENUM,
                    required=True,
                    allowed_values=["any", "same_ball_side", "opposite_ball_side"],
                    description="Retain corridors by relation destination side relative to the ball side.",
                ),
            ],
            evidence_fields=[
                "relation_id",
                "open_frame_id",
                "open_confirm_frame_id",
                "close_frame_id",
                "duration_seconds",
                "target_player_id",
                "destination_side",
                "destination_region",
                "destination_region_type",
                "destination_region_bounds",
                "destination_lane",
                "minimum_clearance_m",
                "limiting_defender_id",
                "source_open_point",
                "target_open_point",
                "source_close_point",
                "target_close_point",
            ],
            limitations=[
                "No pass probability.",
                "No optimality or decision-quality claim.",
                "No receiver body-orientation model.",
                "No offside model in V1 acceptance.",
            ],
        ),
        relation(
            name="opponents_bypassed_by_action",
            version="0.1.0",
            purpose=(
                "Count opposition outfield players who were goal-side of the ball "
                "at action release and behind the ball at controlled reception."
            ),
            outputs=[
                output(
                    name="anchor_evaluations",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "start_frame_id",
                        "end_frame_id",
                        "pass_episode_id",
                        "passer_id",
                        "receiver_id",
                        "release_frame_id",
                        "reception_frame_id",
                        "release_match_time_ms",
                        "reception_match_time_ms",
                        "release_ball_point",
                        "reception_ball_point",
                        "release_passer_point",
                        "reception_receiver_point",
                        "forward_progression_m",
                        "evaluation_status",
                        "coverage_status",
                        "opponents_bypassed_count",
                        "bypassed_player_ids",
                        "candidate_goal_side_player_ids",
                        "expected_active_opposition_outfield_ids",
                        "evaluated_opponent_ids",
                        "missing_active_opponent_ids",
                        "goal_side_buffer_m",
                        "bypassed_buffer_m",
                        "unknown_reason",
                    ],
                ),
                output(
                    name="opponents_bypassed_count",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.NUMBER,
                    cardinality=Cardinality.SINGLE,
                    unit=Unit.COUNT,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=["opponents_bypassed_count", "bypassed_player_ids"],
                ),
                output(
                    name="forward_progression_m",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.NUMBER,
                    cardinality=Cardinality.SINGLE,
                    unit=Unit.METRE,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=["forward_progression_m"],
                ),
                output(
                    name="evaluation_status",
                    temporal_type=TemporalContainer.FRAME_SIGNAL,
                    payload_type=PayloadType.ENUM,
                    cardinality=Cardinality.SINGLE,
                    entity_scope=EntityScope.ANCHOR,
                    allowed_values=["PASS", "FAIL", "UNKNOWN"],
                    evidence_fields=["evaluation_status", "coverage_status", "unknown_reason"],
                ),
            ],
            inputs=[
                input_ref(
                    name="controlled_pass_episodes",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.POSSESSION,
                ),
                input_ref(
                    name="controlled_pass_anchors",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                ),
            ],
            parameters=[
                parameter(
                    name="goal_side_buffer_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    default=typed_number(1.0, Unit.METRE),
                    minimum=0.0,
                    maximum=5.0,
                    description="Release-frame buffer for deciding whether an opponent is goal-side of the ball.",
                ),
                parameter(
                    name="bypassed_buffer_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    default=typed_number(1.0, Unit.METRE),
                    minimum=0.0,
                    maximum=5.0,
                    description="Reception-frame buffer for deciding whether an opponent is behind the ball.",
                ),
            ],
            evidence_fields=[
                "pass_episode_id",
                "passer_id",
                "receiver_id",
                "release_frame_id",
                "reception_frame_id",
                "release_ball_point",
                "reception_ball_point",
                "release_passer_point",
                "reception_receiver_point",
                "forward_progression_m",
                "opponents_bypassed_count",
                "bypassed_player_ids",
                "candidate_goal_side_player_ids",
                "expected_active_opposition_outfield_ids",
                "evaluated_opponent_ids",
                "missing_active_opponent_ids",
            ],
            limitations=[
                "Counts relative ball-position change between release and controlled reception.",
                "Does not prove the pass alone caused every opponent to be bypassed.",
                "Goalkeepers are excluded from the opponent denominator.",
            ],
        ),
        relation(
            name="geometric_progressive_corridor_from_anchor_set",
            version="0.1.0",
            purpose=(
                "Represent a geometrically clear forward connection from a generic "
                "anchor set to an attacking teammate over an interval."
            ),
            outputs=[
                output(
                    name="episodes",
                    temporal_type=TemporalContainer.RELATION_EPISODE_SET,
                    payload_type=PayloadType.RELATION_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.RELATION,
                    evidence_fields=[
                        "relation_id",
                        "open_frame_id",
                        "open_confirm_frame_id",
                        "close_frame_id",
                        "duration_seconds",
                        "target_player_id",
                        "destination_side",
                        "destination_region",
                        "destination_region_type",
                        "destination_region_bounds",
                        "destination_lane",
                        "minimum_clearance_m",
                        "limiting_defender_id",
                        "source_open_point",
                        "target_open_point",
                        "source_close_point",
                        "target_close_point",
                    ],
                ),
                output(
                    name="anchor_evaluations",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.BOOLEAN,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                    evidence_fields=[
                        "anchor_id",
                        "anchor_frame_id",
                        "evaluation_status",
                        "relation_count",
                        "witness_relation_id",
                        "unknown_reason",
                        "state_counts",
                    ],
                ),
            ],
            inputs=[
                input_ref(
                    name="anchors",
                    temporal_type=TemporalContainer.EPISODE_SET,
                    payload_type=PayloadType.ANCHOR_REF,
                    cardinality=Cardinality.COLLECTION,
                    entity_scope=EntityScope.ANCHOR,
                )
            ],
            parameters=[
                parameter(
                    name="max_window_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    required=True,
                    minimum=0.2,
                    maximum=15.0,
                    description="Maximum relation search window after the anchor.",
                ),
                parameter(
                    name="minimum_progression_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=80.0,
                    description="Minimum forward progression from source to target.",
                ),
                parameter(
                    name="minimum_segment_length_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=80.0,
                    description="Minimum source-target segment length.",
                ),
                parameter(
                    name="maximum_segment_length_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=100.0,
                    description="Maximum source-target segment length.",
                ),
                parameter(
                    name="minimum_clearance_m",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.METRE,
                    required=True,
                    minimum=0.0,
                    maximum=40.0,
                    description="Minimum defender clearance from the source-target segment.",
                ),
                parameter(
                    name="open_after_frames",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.COUNT,
                    required=True,
                    minimum=1.0,
                    maximum=100.0,
                    description="Frames required before a corridor is considered open.",
                ),
                parameter(
                    name="close_after_frames",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.COUNT,
                    required=True,
                    minimum=1.0,
                    maximum=100.0,
                    description="Frames required before a corridor is considered closed.",
                ),
                parameter(
                    name="minimum_duration_seconds",
                    payload_type=PayloadType.NUMBER,
                    unit=Unit.SECOND,
                    required=True,
                    minimum=0.0,
                    maximum=15.0,
                    description="Minimum open duration retained in the relation output.",
                ),
                parameter(
                    name="side_filter",
                    payload_type=PayloadType.ENUM,
                    required=True,
                    allowed_values=["any", "same_ball_side", "opposite_ball_side"],
                    description="Retain corridors by relation destination side relative to the ball side.",
                ),
            ],
            evidence_fields=[
                "relation_id",
                "open_frame_id",
                "open_confirm_frame_id",
                "close_frame_id",
                "duration_seconds",
                "target_player_id",
                "destination_side",
                "destination_region",
                "destination_region_type",
                "destination_region_bounds",
                "destination_lane",
                "minimum_clearance_m",
                "limiting_defender_id",
                "source_open_point",
                "target_open_point",
                "source_close_point",
                "target_close_point",
            ],
            limitations=[
                "No pass probability.",
                "No optimality or decision-quality claim.",
                "No player intent, causation, or missed-opportunity claim.",
                "No receiver body-orientation or offside model.",
            ],
        )
    ]


def default_operators() -> list[OperatorSignature]:
    return [
        OperatorSignature(
            name="gt",
            version="1.0.0",
            purpose="Compare a numeric signal to a strict lower numeric threshold.",
            input_temporal_types=[TemporalContainer.SCALAR, TemporalContainer.FRAME_SIGNAL],
            input_payload_types=[PayloadType.NUMBER],
            input_cardinalities=[
                Cardinality.SINGLE,
                Cardinality.PER_PLAYER,
                Cardinality.PER_TEAM,
            ],
            compare_payload_types=[PayloadType.NUMBER],
            compare_required=True,
            compare_unit_must_match=True,
            output_temporal_type=TemporalContainer.FRAME_SIGNAL,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.SINGLE,
        ),
        OperatorSignature(
            name="gte",
            version="1.0.0",
            purpose="Compare a numeric signal to a numeric threshold.",
            input_temporal_types=[TemporalContainer.SCALAR, TemporalContainer.FRAME_SIGNAL],
            input_payload_types=[PayloadType.NUMBER],
            input_cardinalities=[
                Cardinality.SINGLE,
                Cardinality.PER_PLAYER,
                Cardinality.PER_TEAM,
            ],
            compare_payload_types=[PayloadType.NUMBER],
            compare_required=True,
            compare_unit_must_match=True,
            output_temporal_type=TemporalContainer.FRAME_SIGNAL,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.SINGLE,
        ),
        OperatorSignature(
            name="lte",
            version="1.0.0",
            purpose="Compare a numeric signal to an upper numeric threshold.",
            input_temporal_types=[TemporalContainer.SCALAR, TemporalContainer.FRAME_SIGNAL],
            input_payload_types=[PayloadType.NUMBER],
            input_cardinalities=[
                Cardinality.SINGLE,
                Cardinality.PER_PLAYER,
                Cardinality.PER_TEAM,
            ],
            compare_payload_types=[PayloadType.NUMBER],
            compare_required=True,
            compare_unit_must_match=True,
            output_temporal_type=TemporalContainer.FRAME_SIGNAL,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.SINGLE,
        ),
        OperatorSignature(
            name="eq",
            version="1.0.0",
            purpose="Compare a signal to an equal typed value.",
            input_temporal_types=[
                TemporalContainer.SCALAR,
                TemporalContainer.FRAME_SIGNAL,
                TemporalContainer.EPISODE_SET,
            ],
            input_payload_types=[
                PayloadType.BOOLEAN,
                PayloadType.NUMBER,
                PayloadType.ENUM,
                PayloadType.ENTITY_REF,
                PayloadType.TEAM_REF,
                PayloadType.REGION_REF,
            ],
            input_cardinalities=[
                Cardinality.SINGLE,
                Cardinality.PER_PLAYER,
                Cardinality.PER_TEAM,
            ],
            compare_payload_types=[
                PayloadType.BOOLEAN,
                PayloadType.NUMBER,
                PayloadType.ENUM,
                PayloadType.ENTITY_REF,
                PayloadType.TEAM_REF,
                PayloadType.REGION_REF,
            ],
            compare_required=True,
            compare_unit_must_match=True,
            output_temporal_type=TemporalContainer.FRAME_SIGNAL,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.SINGLE,
        ),
        OperatorSignature(
            name="neq",
            version="1.0.0",
            purpose="Compare a signal to a non-equal typed value.",
            input_temporal_types=[
                TemporalContainer.SCALAR,
                TemporalContainer.FRAME_SIGNAL,
                TemporalContainer.EPISODE_SET,
            ],
            input_payload_types=[
                PayloadType.BOOLEAN,
                PayloadType.NUMBER,
                PayloadType.ENUM,
                PayloadType.ENTITY_REF,
                PayloadType.TEAM_REF,
                PayloadType.REGION_REF,
            ],
            input_cardinalities=[
                Cardinality.SINGLE,
                Cardinality.PER_PLAYER,
                Cardinality.PER_TEAM,
            ],
            compare_payload_types=[
                PayloadType.BOOLEAN,
                PayloadType.NUMBER,
                PayloadType.ENUM,
                PayloadType.ENTITY_REF,
                PayloadType.TEAM_REF,
                PayloadType.REGION_REF,
            ],
            compare_required=True,
            compare_unit_must_match=True,
            output_temporal_type=TemporalContainer.FRAME_SIGNAL,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.SINGLE,
        ),
        OperatorSignature(
            name="persists_for",
            version="1.0.0",
            purpose="Promote a boolean frame signal to intervals after minimum duration.",
            input_temporal_types=[TemporalContainer.FRAME_SIGNAL],
            input_payload_types=[PayloadType.BOOLEAN],
            input_cardinalities=[Cardinality.SINGLE, Cardinality.PER_PLAYER, Cardinality.PER_TEAM],
            duration_required=True,
            output_temporal_type=TemporalContainer.EPISODE_SET,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.COLLECTION,
            limitations=["UNKNOWN remains UNKNOWN; absence is not converted to FALSE."],
        ),
        OperatorSignature(
            name="exists",
            version="1.0.0",
            purpose="Test whether a boolean episode or anchor-evaluation collection exists.",
            input_temporal_types=[
                TemporalContainer.EPISODE_SET,
            ],
            input_payload_types=[PayloadType.BOOLEAN],
            input_cardinalities=[Cardinality.COLLECTION],
            output_temporal_type=TemporalContainer.FRAME_SIGNAL,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.SINGLE,
        ),
        OperatorSignature(
            name="count_at_least",
            version="1.0.0",
            purpose="Count a boolean or entity collection and compare to a count threshold.",
            input_temporal_types=[
                TemporalContainer.EPISODE_SET,
            ],
            input_payload_types=[PayloadType.ENTITY_SET, PayloadType.BOOLEAN],
            input_cardinalities=[Cardinality.COLLECTION],
            compare_payload_types=[PayloadType.NUMBER],
            compare_required=True,
            output_temporal_type=TemporalContainer.FRAME_SIGNAL,
            output_payload_type=PayloadType.BOOLEAN,
            output_cardinality=Cardinality.SINGLE,
        ),
    ]


def default_catalog() -> CapabilityCatalog:
    return CapabilityCatalog(
        primitives=default_primitives(),
        relations=default_relations(),
        operators=default_operators(),
        default_complexity_limits=ComplexityLimits(
            max_plan_nodes=40,
            max_nesting_depth=12,
            max_temporal_horizon_seconds=15.0,
            max_returned_moments=500,
            max_relations_per_anchor=1000,
            max_execution_cost=100000,
        ),
    )
